services:
  - type: web
    name: ai-stocks-companion
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/intelligent-stock-market-companion
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 