services:
  - type: web
    name: ai-stocks-companion
    env: static
    buildCommand: npm install -g @angular/cli && npm install && ng build --configuration production
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 